#!groovy

// Generated by IBM TransformationAdvisor
// Fri Jul 05 15:38:04 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}